<a href="https://colab.research.google.com/github/hblacksmith/Clustering/blob/main/MSc_DTS_Cosine_TfidfVectorizer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [72]:
# Import Libraries
import pandas as pd
import numpy as np

In [73]:
# Define the Documents
ld1 = "Leadership. Show pride and passion for public service. Create and engage others in delivering a shared vision. Value difference, diversity and inclusion, ensuring fairness and opportunity for all. Show pride and passion for your work and positive, inclusive engagement with your team. Understand your areas of responsibility and display awareness of the wider impact of your actions. Proactively role model and promote an inclusive workplace, promptly dealing with inappropriate language and behaviours when they arise, including any instances of discrimination or misconduct. Give praise and credit to colleagues and stakeholders where appropriate. Advocated Collaborated commitment coordinated delegation determination directed ethical focused improved modernised motivated negotiated optimised passionate improved piloted pioneered planned prompted propelled purpose revitalised reliable shaped spearheaded supported trained transformed"

data1 = "Working as a Census 2021 Team Leader, I had to motivate and manage Census Officers, tasked with encouraging people in assigned areas to complete their Census 2021 online questionnaire. I had to achieve a response rate of 92% within four weeks. I analysed and reviewed the areas I was allocated and ranked them in order of difficulties for response rate. I communicated this information to my team on a weekly basis using powerpoint presentations in regular team meetings. I also identified my strongest officers, who are very persuasive in my team and allocated to those officers areas that are very difficult to get a response from. I motivated my team on a daily basis and maintained effective relationship with every officer to ensure that they perform to the best of their ability. I was able to steer my team under my leadership to get a record breaking response rate for my assigned areas. The response rate for my assigned area at the end of the operation was over 95%, which is 3% more than the set target of 92%. My area manager was very pleased with the outcome in my area and my officers  were very happy to "
data2 = "to competitive rugby. The sport taught me the importance of teamwork and a structured partition of responsibilities and functions. Playing rugby in a leading position allowed me to develop a propensity towards inclusivity and fairness, thus an awareness regarding the importance of team members' diverse qualities and their centrality for success. Moreover, I believe that a shared passion, trust, and a supportive attitude are the keys to a successful and efficient collective. Therefore, the role of a leader is to provide a team with ways to convey their energies into a common objective through such values. A significant occasion in which I was able to transfer these leadership abilities and attitudes was a semester long, simulated negotiation project. Due to my proactive personality, I took on a leadership role. After a preliminary meeting, I set a deadline by which we should have researched different areas and discussed the general objectives to pursue. By the time of the deadline the group met and, in accordance with the team, I proposed a network organisation in which each member would research each negotiating actor's interests. The group then utilised a project platform to share information and communicate. The team would then meet weekly to discuss and adjust the negotiating strategy according to the new information gathered. The group was extremely involved and, as a result, successful, achieving the highest mark in the class."
data3 = "I worked for M&S for 5 years, and I was able to work in a number of stores and departments. This meant I was exposed to the different ways each store tackled tasks. Upon starting in a new store, I noticed a large amount of product ended up damaged, or was left in the warehouse to expire. I recognised this issue was a result of how shelves were being filled; Each time a shelf was filled a new box was opened, instead of finishing one that was already open, and loose items were often forgotten about. I used my initiative to start a method that would help prevent products from becoming damaged. I did this by using crates to store products when there was no space left on the shelf, and placed these at the end of each aisle in the warehouse. I asked my manager to get staff to fill using these crates before opening new boxes, and encouraged my colleagues to do the same. I explained my reasoning,  and also communicated this in ways I knew would resonate with them. For example, by mentioning how annoying it is when boxes fall over, and how these creates would prevent this from happening. I received a positive response from my manager by doing this, and my colleagues were happy to use this new method to prevent product damage. "
data4 = "Situation: Once my manager was off from work for a week and told me to lead the project. There were some requests that had to be done in that week urgently. Task: Had to keep everything on the right track in the absence of him. Action: I hold the meeting with the other team mates and asked for their views and opinions as well. I presented the list of work to be done and assigned them to their choice of interest. Result: With collective contribution of the team, I was able to lead the project effectively."
data5 = "I was part of the committee that started the first Bengali Society at my university. As Vice President, my responsibilities included creating meeting agendas and arranging committee meetings, booking venues for all events, managing society emails and keeping actions logs for all committee members and events. However, as we were just starting out as a small team I was constantly helping our team members by inputting my ideas across all the committee roles. One of our main priorities for the society was to establish the foundations for the following years as this would be vital towards sustaining and growing the society. I made sure that all team members worked together so that all of our events were regularly promoted across all the social media pages we had set up for the society, in order to maintain current society members and also recruit new ones. This was an important task as the number of members the society had made a massive impact on whether the society would continue for consecutive years. Furthermore, once we had enough members interested in our society it was vital to keep them engaged during the events. This was done by ensuring we brought a lot of energy and had interactive elements to the events such as games and challenges. Overall, I would say we were extremely successful in the building of the society and were able to set strong foundations for the following year which can be seen as the society has since doubled its members."

documents = [ld1,data1, data2, data3, data4, data5]

In [74]:
# To compute the cosine similarity, you need the word count of the words in each document.
from sklearn.feature_extraction.text import TfidfVectorizer

In [75]:
# Create the Document Matrix
tfidf_vectorizer = TfidfVectorizer(stop_words='english')
tfidf_vectorizer = TfidfVectorizer()
sparse_matrix = tfidf_vectorizer.fit_transform(documents)

In [76]:
#OPTINAL: Convert Sparse Matrix into DataFrame to Pandas DataFrame to see word frequencies
doc_term_matrix = sparse_matrix.todense()
df = pd.DataFrame(doc_term_matrix, columns=tfidf_vectorizer.get_feature_names_out(), index=['ld1', 'data1', 'data2', 'data3', 'data4', 'data5',])
#df

In [77]:
# Compute Cosine Similarity
from sklearn.metrics.pairwise import cosine_similarity
print(cosine_similarity(df, df))

[[1.         0.15065258 0.22944999 0.15910421 0.16919062 0.1422081 ]
 [0.15065258 1.         0.34801738 0.33573546 0.35184856 0.24169508]
 [0.22944999 0.34801738 1.         0.34104342 0.44397301 0.346376  ]
 [0.15910421 0.33573546 0.34104342 1.         0.30893291 0.27153539]
 [0.16919062 0.35184856 0.44397301 0.30893291 1.         0.33486881]
 [0.1422081  0.24169508 0.346376   0.27153539 0.33486881 1.        ]]


In [78]:
# For word vecotrs need a word embedding model
import gensim
from gensim.matutils import softcossim
from gensim import corpora
import gensim.downloader as api
from gensim.utils import simple_preprocess

In [79]:
# Download the FastText model
fasttext_model1300 = api.load('fasttext-wiki-news-subwords-300')

In [80]:
# Prepare a dictionary and corpus
dictionary = corpora.Dictionary([simple_preprocess(doc) for doc in documents])

In [81]:
#Prepare the similarity matrix
similarity_matrix = fasttext_model1300.similarity_matrix(dictionary, tfidf=None, threshold=0.0, exponent=2.0, nonzero_limit=100)

In [82]:
# Convert the sentences into bag-of-words vectors
sent_1 = dictionary.doc2bow(simple_preprocess(ld1))    
sent_2 = dictionary.doc2bow(simple_preprocess(data1))  
sent_3 = dictionary.doc2bow(simple_preprocess(data2))  
sent_4 = dictionary.doc2bow(simple_preprocess(data3))  
sent_5 = dictionary.doc2bow(simple_preprocess(data4))  
sent_6 = dictionary.doc2bow(simple_preprocess(data5))

sentences = [sent_1, sent_2, sent_3, sent_4, sent_5, sent_6]

In [83]:
#Compare soft cosine of all documents 
import numpy as np
import pandas as pd

def create_soft_cossim_matrix(sentences):
    len_array = np.arange(len(sentences))
    xx, yy = np.meshgrid(len_array, len_array)
    cossim_mat = pd.DataFrame([[round(softcossim(sentences[i],sentences[j], similarity_matrix) ,2) for i, j in zip(x,y)] for y, x in zip(xx, yy)])
    return cossim_mat

create_soft_cossim_matrix(sentences)

0     1     2     3     4     5
0  1.00  0.56  0.66  0.54  0.58  0.58
1  0.56  1.00  0.84  0.82  0.84  0.78
2  0.66  0.84  1.00  0.83  0.86  0.84
3  0.54  0.82  0.83  1.00  0.86  0.82
4  0.58  0.84  0.86  0.86  1.00  0.84
5  0.58  0.78  0.84  0.82  0.84  1.00