<a href="https://colab.research.google.com/github/hblacksmith/Clustering/blob/main/MSc_DTS_New_ML_Classifier_Model2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Natural Language Processing

## Importing the libraries

In [938]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [939]:
dataset = pd.read_csv('AppData2.csv', encoding='ISO-8859–1')

## Cleaning the texts

In [940]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 100):
  text = re.sub('[^a-zA-Z]', ' ', dataset['Text'][i])
  text = text.lower()
  text = text.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  text = [ps.stem(word) for word in text if not word in set(all_stopwords)]
  text = ' '.join(text)
  corpus.append(text)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [941]:
# View all words in corpus
#print(corpus)

## Creating the Bag of Words model

In [942]:
from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [943]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 0)

## Training the Naive Bayes model on the Training set

In [944]:
#GaussianNB = 0.875 accuracy
#from sklearn.naive_bayes import GaussianNB
#classifier = GaussianNB()
#classifier.fit(X_train, y_train)

In [945]:
#Multinomial NB = 0.875 accuracy
#from sklearn.naive_bayes import MultinomialNB
#classifier = MultinomialNB()
#classifier.fit(X_train, y_train)

In [946]:
#SVC = 0.875 accuracy
from sklearn.svm import SVC
classifier = SVC()
classifier.fit(X_train, y_train)

SVC()

## Predicting the Test set results

In [947]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


## Measuring Performance

In [948]:
#Confusion Matrix - Accuracy
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[35  0]
 [ 5  0]]


0.875

In [949]:
#What the model got right
y_true = np.array([0,0,0,0,0,1,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0])
y_pred = np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0])
true_positives = ((y_pred == y_true) & (y_pred == 1)).sum()
true_positives

1

In [950]:
true_negatives = ((y_pred == y_true) & (y_pred == 0)).sum()
true_negatives

24

In [951]:
#What the model got wrong
false_positives = ((y_pred != y_true) & (y_pred == 1)).sum()
false_positives

1

In [952]:
false_negatives = ((y_pred != y_true) & (y_pred == 0)).sum()
false_negatives

4

In [953]:
#Precision - how many true labels did the model detect (1.0 = NO FALSE POSITIVES)
precision = true_positives / (true_positives + false_positives)
precision

0.5

In [954]:
#Recall - how many positive examples were detected in the dataset
recall = true_positives / (true_positives + false_negatives)
recall

0.2

In [955]:
#RMSE - Root Mean Square Error
rmse = np.sqrt((y_true - y_pred) ** 2 / len(y_true))
rmse

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.18257419, 0.        , 0.        , 0.        , 0.18257419,
       0.        , 0.18257419, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.18257419,
       0.        , 0.        , 0.        , 0.18257419, 0.        ])

## Predicting if a single statement is Pass [1] or Reject [0]

### Positive review

In [956]:
new_statement = "Being a strong, committed and confident leader, I understand there is a requirement within this role to direct and influence others to achieve the national objectives of the Civil Service. To provide evidence of my ability to lead, in a previous role I was required to manage and direct a team of people to achieve difficult and challenging projects on a recurring basis. When I first joined the team as their leader, I was concerned as to the lack of direction and motivation within the team, and so I started setting concise team values, creating action plans and conducting performance reviews for all members of staff that were designed to get us where we needed to be. Although some team members were initially reluctant to the changes I was implementing, I persevered and influenced them to believe my chosen course of action was the right one for our long-term goals and the organization's core mission. At all times, I ensured team members had the same opportunities in respect of career advancement, and I often asked everyone for their opinion on how the team could move forward and achieve its objectives. By involving my team members in the action plan execution process, and by valuing their views and opinions, we were able to consistently achieve our goals. More often than not, we were praised by senior management for our ability to deliver projects within very tight deadlines. As a leader within the Civil Service, I will consistently deliver on my objectives."

new_statement = re.sub('[^a-zA-Z]', ' ', new_statement)
new_statement = new_statement.lower()
new_statement = new_statement.split()
ps = PorterStemmer()
all_stopwords = stopwords.words('english')
all_stopwords.remove('not')
new_statement = [ps.stem(word) for word in new_statement if not word in set(all_stopwords)]
new_statement = ' '.join(new_statement)
new_corpus = [new_statement]
new_X_test = cv.transform(new_corpus).toarray()
new_y_pred = classifier.predict(new_X_test)
print(new_y_pred)

[1]


The review was correctly predicted as positive by our model.

### Negative review

**Solution:** We just repeat the same text preprocessing process we did before, but this time with a single review.

In [957]:
new_statement = "Promote diversity, inclusion and equality of opportunity, respecting difference and external experience. Welcome and respond to views and challenges from others, despite any conflicting pressures to ignore or give in to them. Stand by, promote or defend own and team’s actions and decisions where needed. Seek out shared interests beyond own area of responsibility, understanding the extent of the impact actions have on the organisation. Inspire and motivate teams to be fully engaged in their work and dedicated to their role. "
new_statement = re.sub('[^a-zA-Z]', ' ', new_statement)
new_statement = new_statement.lower()
new_statement = new_statement.split()
ps = PorterStemmer()
all_stopwords = stopwords.words('english')
all_stopwords.remove('not')
new_statement = [ps.stem(word) for word in new_statement if not word in set(all_stopwords)]
new_statement = ' '.join(new_statement)
new_corpus = [new_statement]
new_X_test = cv.transform(new_corpus).toarray()
new_y_pred = classifier.predict(new_X_test)
print(new_y_pred)

[0]


The review was correctly predicted as negative by our model.