<a href="https://colab.research.google.com/github/hblacksmith/Clustering/blob/main/MSc_DTS_Cosine_TfidfVectorizer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [79]:
# Import Libraries
import pandas as pd
import numpy as np

In [80]:
# Define the Documents
ld1 = "Leadership. Show pride and passion for public service. Create and engage others in delivering a shared vision. Value difference, diversity and inclusion, ensuring fairness and opportunity for all. Show pride and passion for your work and positive, inclusive engagement with your team. Understand your areas of responsibility and display awareness of the wider impact of your actions. Proactively role model and promote an inclusive workplace, promptly dealing with inappropriate language and behaviours when they arise, including any instances of discrimination or misconduct. Give praise and credit to colleagues and stakeholders where appropriate. Advocated Collaborated commitment coordinated delegation determination directed ethical focused improved modernised motivated negotiated optimised passionate improved piloted pioneered planned prompted propelled purpose revitalised reliable shaped spearheaded supported trained transformed"

data1 = "When I worked for British Airways, we had a new boarding process software introduced known as AMADEUS JFE which was quite challenging and complicated at the beginning. We all had training on that new software and still many of my colleagues used find it difficult to navigate. I took that training very seriously from the beginning and learnt almost all the aspects as details as possible because I knew embracing new change has no alternative specially when it comes to learning new IT Skill. Based on an internal survey it turned out almost 73% of employees were still finding the software difficult to use. In the meantime, I focused on using the software for both boarding process and at check-in so that I could learn all the functionality quicker than others. This is how I took this opportunity to develop myself ahead of others. In the meantime, Management was looking for colleagues who already managed to learn the software adequately so that they can utilize those colleague's expertise to retrain rest of the colleagues who were still struggling with that software. I volunteer for this opportunity and was assigned for three weeks to retrain part of my colleagues. During that time, I was taken off from my daily routine job role and made SME (Subject Matter Expert) so that I can focus on training my fellow colleagues. I managed to retrain 27 of my colleagues onto that software and developed their skill to an optimal level to achieve the goal."
data2 = "I put myself forward for enrolment onto the Siemens Supervisor Development Programme, which consists of modules on coaching, people management, presenting and finance, as I realised my leadership skills could be strengthened. Following this, whilst on a placement with the digital team, I opted to put these skills to use by leading the implementation of Agile methods within a sub-team of 5 graduates and apprentices. Acting as Scrum Master, I scheduled a kick-off event where I explained the concept of Agile working, the different roles, events and outcomes of the sprint cycle to the team. Subsequently, I organised and lead the initial sprint planning session, and set up daily stand-up meetings in which the team would discuss their progress and raise attention to any blockers. In time these stand-up meetings became increasingly autonomous and team led. Where necessary, I would facilitate collaboration with internal and external team members to overcome blockers. The team responded well to the Agile style of leading from the back and achieved a much more transparent, collaborative way of working. The practices I laid out are still used today, which is a personal success for me and provides me with external validation of my ability to lead a project effectively. I welcome future opportunities to develop my skills in leadership and see it as a skill which I will continue develop throughout the entirety of my professional career."
data3 = "I am helping organise a puzzle hunt in which I am leading a factchecking team. The hunt has entered the stage where factchecking has become important. I have had to organise the rest of the team into groups in order to make sure that the checks are done effectively, and tackle any questions they have about the system in place. This means we have an efficient and robust system to carry forward for later instances."
data4 = "At the start of 2021 I heard news that the local county council was offering a business grant to help small businesses to buy capital equipment to help grow and recover from the impact of Covid-19. I discussed it with my bosses as to what the grant could be used for and researched as to whether our business would qualify. Then, I gathered a list of what information would be required and allocated the tasks to my colleagues, such as contacting a range of suppliers for quotes and gathering information from the accountants such as yearly profit totals. I applied for the grant using this information and the application was successful."
data5 = "A key responsibility as store manager was smooth running of all operational aspects of the store. I was expecting a big delivery from the depot in preparation for Easter. having a relatively smaller team of five staff operating during the peak season I knew it would be a busy and proactively planned for the day. I invited the whole team to discuss the tasks ahead of us. My management program came in very handy as I applied team working and leadership strategies including brainstorming. I had discussions where I was open to suggestions allowing everyone to feel part of the decision making process. This approach made my team feel valued and they were happy to lead on respective tasks that I assigned. I put a timetable together and in line with Health & Safety regulations organised break times and reassigned roles such that two staff were operating at delivery and checkouts at any given time. Showing leadership, I paired up with the fifth staff to ensure shop floor was fully stocked efficiently upon stock delivery. As a result, the team managed to run smoothly on the day with no issues reported. The shop floor was fully topped up and the warehouse was well organised. My manager inspected the store and was incredibly happy with the results and profit. I was extremely proud of my team and treated them to doughnuts. Having built this good working relationship with my team, I was able to deliver similar good results going forward."
documents = [ld1, data1, data2, data3, data4, data5]

In [81]:
# To compute the cosine similarity, you need the word count of the words in each document.
from sklearn.feature_extraction.text import TfidfVectorizer

In [82]:
# Create the Document Matrix
tfidf_vectorizer = TfidfVectorizer(stop_words='english')
tfidf_vectorizer = TfidfVectorizer()
sparse_matrix = tfidf_vectorizer.fit_transform(documents)

In [83]:
#OPTINAL: Convert Sparse Matrix into DataFrame to Pandas DataFrame to see word frequencies
doc_term_matrix = sparse_matrix.todense()
df = pd.DataFrame(doc_term_matrix, columns=tfidf_vectorizer.get_feature_names_out(), index=['ld1', 'data1', 'data2', 'data3', 'data4', 'data5',])
#df

In [84]:
# Compute Cosine Similarity
from sklearn.metrics.pairwise import cosine_similarity
print(cosine_similarity(df, df))

[[1.         0.16733953 0.21016474 0.1086124  0.15456441 0.19558674]
 [0.16733953 1.         0.31678838 0.20960513 0.31030165 0.3612211 ]
 [0.21016474 0.31678838 1.         0.27602557 0.33368017 0.43622507]
 [0.1086124  0.20960513 0.27602557 1.         0.17801016 0.2328842 ]
 [0.15456441 0.31030165 0.33368017 0.17801016 1.         0.36466149]
 [0.19558674 0.3612211  0.43622507 0.2328842  0.36466149 1.        ]]


In [85]:
# For word vectors they need a word embedding model
import gensim
from gensim.matutils import softcossim
from gensim import corpora
import gensim.downloader as api
from gensim.utils import simple_preprocess

In [86]:
# Download the FastText model
fasttext_model1300 = api.load('fasttext-wiki-news-subwords-300')

In [87]:
# Prepare a dictionary and corpus
dictionary = corpora.Dictionary([simple_preprocess(doc) for doc in documents])

In [88]:
#Prepare the similarity matrix
similarity_matrix = fasttext_model1300.similarity_matrix(dictionary, tfidf=None, threshold=0.0, exponent=2.0, nonzero_limit=100)

In [89]:
# Convert the sentences into bag-of-words vectors
sent_1 = dictionary.doc2bow(simple_preprocess(ld1))    
sent_2 = dictionary.doc2bow(simple_preprocess(data1))  
sent_3 = dictionary.doc2bow(simple_preprocess(data2))  
sent_4 = dictionary.doc2bow(simple_preprocess(data3))  
sent_5 = dictionary.doc2bow(simple_preprocess(data4))  
sent_6 = dictionary.doc2bow(simple_preprocess(data5))

sentences = [sent_1, sent_2, sent_3, sent_4, sent_5, sent_6]

In [90]:
#Compare soft cosine of all documents 
import numpy as np
import pandas as pd

def create_soft_cossim_matrix(sentences):
    len_array = np.arange(len(sentences))
    xx, yy = np.meshgrid(len_array, len_array)
    cossim_mat = pd.DataFrame([[round(softcossim(sentences[i],sentences[j], similarity_matrix) ,2) for i, j in zip(x,y)] for y, x in zip(xx, yy)])
    return cossim_mat

create_soft_cossim_matrix(sentences)

0     1     2     3     4     5
0  1.00  0.59  0.65  0.52  0.59  0.61
1  0.59  1.00  0.85  0.76  0.85  0.84
2  0.65  0.85  1.00  0.77  0.83  0.87
3  0.52  0.76  0.77  1.00  0.72  0.75
4  0.59  0.85  0.83  0.72  1.00  0.81
5  0.61  0.84  0.87  0.75  0.81  1.00